### ISSUE TITLE
no select/copy/paste when opening a .txt file from filemanager

### ISSUE THREAD

**Issue by phunkular** [billthefarmer/editor#33]
on fdroid version 1.12, the select/copy/paste function doesn't work when accessing text files from a file manager.

Changing the size of the text or font size restores this functionality.

thanks

**Comment by billthefarmer** [comment]
That's because due to a request #25, files are opened read only. Touch the edit button in the toolbar, or long touch on the display, or change almost anything on the menu to enable editing. Read the [README](https://github.com/billthefarmer/editor/blob/master/README.md) or the [release notes](https://github.com/billthefarmer/editor/releases) to see changes in functionality.

**Comment by phunkular** [comment]
hi, I just started using this app so I don't know much about what's changed (apart from looking at a couple of issues before posting). The problem would persist even in editing mode with the keyboard out and text being typed. The only way around it was to change the font somehow.

Doesn't matter now though as your latest version just got pushed through fdroid and the problem has disappeared (I can select text and copy in either mode and even when opened from a file manager).

**Comment by phunkular** [comment]
OK I take that back, by some fluke it worked correctly a few times before returning to previous behavior. So this happens when opening the file from my file manager, not when going through editor app first and then using the same file manager to select a file.

I am using a MIUI device and the file manager I'm using is available on Google play as Mi Explorer I believe (Xiaomi Inc.). I just tried Amaze file manager though too and got the same issue.

When I have suggestions enabled there is a very subtle flash in the suggestions bar when long pressing (and when the select/copy/paste dialog should appear but doesn't).

To be clear: when I open the Editor app first and then select 'open file' and use my file manager to select the file then copy/past works. When I open a .txt file directly from my file manager, then copy paste doesn't work. When this happens, changing the font will make copy/paste work.

**Comment by phunkular** [comment]
On further testing, copy/paste will intermittently work as expected when going directly from the filemanager (maybe 1/100 times on average). 

Behavior is the same regardless of file manager used.

Can't pinpoint why it works on some occasions with exactly the same conditions.

The only clue is changing the font fixes the issue.

Anything I can check/test? There is an app on droid to intercept intents if that might help?

**Comment by billthefarmer** [comment]
I can't reproduce this, I've tested it on two different devices. I've used the app you mention to discover exactly what file managers and other apps send in an intent, but it wouldn't help in this case. Changing the font or almost anything else enables editing by default because it resets the input type. I explained this [here](https://github.com/billthefarmer/editor/issues/31#issuecomment-347446318).

The exact behaviour is - on opening a file by any means the input type is set to 'none' and editing is disabled, touching or scrolling the display does nothing. On a long touch editing is enabled, the keyboard pops up, a flashing cursor appears and suggestions are shown if enabled. Another long touch will pop up the copy/paste menu. On touching the edit button nothing happens, but a touch on the display pops up the keyboard, the flashing cursor appears and suggestions are shown if enabled. A long touch will pop up the copy/paste menu. There may be subtle variations with different versions of android or different devices, but android apps can only use the published API and assume that it works as described.

**Comment by phunkular** [comment]
Ok, well what is clear is that on my phone running MIUI 9/Andorid 6.0.1, there is a difference in behaviour in how the Editor app works based on whether or not I open a text file from a file manager or starting from the app itself. When going through a file manager, the select/copy/paste function is inhibited until redrawing the fonts by changing either size or typeface whether in edit mode or not.

Apart from recording a video of what's happening I don't really know what else I could offer, sorry.

**Comment by arschficken** [comment]
I have confirmed this bug in Editor 1.13 on Android 6.0.1. When using a file manager to open a file in Editor, long press enables editing (and edit suggestions are now correctly shown), but subsequently neither long pressing nor double tapping bring up the copy/paste functionality.

Changing the text size or typeface restores copy/paste functionality, whereas toggling auto save, word wrap, or suggestions doesn't.

Suspect it's an Android 6 thing, like [the theme change issue](https://github.com/billthefarmer/editor/issues/23).

**Comment by billthefarmer** [comment]
I still can't reproduce this. I have attached a video of testing version 1.13 on a Nexus 10 running android 6.01. The sequence is:
* Open the file manager
* Open the text file
* Long touch on the display - keyboard pops up as above
* Long touch on the display - copy/paste menu pops up
* Back to the file manager
* Open the text file
* Touch the edit icon - nothing happens
* Touch the display - keyboard pops up
* Long touch on the display - copy/paste menu pops up
The video is zipped because Github doesn't like MP4 files. It displays fine in android and in windows but not using [MPC-HC](https://mpc-hc.org) for some reason.

[ed.zip](https://github.com/billthefarmer/editor/files/1530934/ed.zip)

**Comment by billthefarmer** [comment]
I have managed to reproduce this on an emulator running android 6. I have tested a workaround that changes the text size and then restores it which seems to work. That will be in the next version.

**Comment by arschficken** [comment]
Bill, you're a legend. Thanks for all your work.

**Comment by arschficken** [comment]
Confirmed fixed in 1.14.

**Comment by downloaderfan** [comment]
I'm facing this bug on v1.15. Toggling suggestions fixes the issue, but I have to do this every time I launch a text file from File Explorer.
Video - https://streamable.com/3kpp0

SlimROM 7.1.2 Nougat
Xiaomi Redmi Note 3

**Comment by billthefarmer** [comment]
I have released a new version with another workaround that toggles suggestions

**Comment by downloaderfan** [comment]
I'm pretty new to F-Droid & from a quick search, it seems it'll take days for the update to show up, so will definitely test the newer version when it appears.

**Comment by downloaderfan** [comment]
It's been a week & I still see v1.15 & not the update. Wow, F-Droid is really really slow.

**Comment by billthefarmer** [comment]
It varies wildly. I have had apps published the next day. This version is in their [wiki](https://f-droid.org/wiki/page/org.billthefarmer.editor), but they haven't built it yet.

**Comment by downloaderfan** [comment]
It says on their wiki
"We can't build this version: The build for this version appears to have failed. Check the build log."
I don't think this is normal.

**Comment by billthefarmer** [comment]
They haven't tried to [build](https://f-droid.org/wiki/page/org.billthefarmer.editor/lastbuild_115) it. The build log link is to a non-existent page. It looks like they tried to build some apps yesterday, but they [failed](https://f-droid.org/wiki/page/com.github.axet.audiorecorder/lastbuild_235).
